name: WebComponents Package publication
on:
  push:
    branches:
      - fix-release-npm
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
      - run: |
          cd webc-omponents
          npm publish:package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: "24.x"
          registry-url: 'https://npm.pkg.github.com'
      - run: |
          cd web-components
          npm publish:package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}